### ISSUE TITLE
feature request :: hierachie of fields

### ISSUE THREAD

**Issue by AndrassGray** [clivebeckett/grav-plugin-admin-addon-media-metadata#10]
Really nice plugin! Thanks for putting energy into this.

Would you think that a hierarchy of fields is possible? To explain, I have a multi-language site, and title and stuff changes with the language.

My current media yaml looks like this:

```
sku: sku
tags: tag1, tag2, tag3

title:
  en: english title
  fr: titre français
  de: deutscher titel

alt:
  en: english alt
  fr: alt français
  de: düsseldorfer alt
```

Any hope ? Thanks a ton!

**Comment by renards** [comment]
Very good idea. I think it's a must have when working with a multi-language site.
However, I would prefer the following structure:

```
en:
  sku: sku
  tags: tag1, tag2, tag3
  title: english title
  alt: english alt
fr:
  sku: sku
  tags: tag1, tag2, tag3
  title: titre français
  alt: alt français
de:
  sku: sku
  tags: tag1, tag2, tag3
  title: deutscher titel
  alt: diebels alt
```

You can then use this Twig Snippet to access the translations, for example:

`image.meta[language].alt`
