### ISSUE TITLE
Does not work with flex-objects

### ISSUE THREAD

**Issue by bitstarr** [clivebeckett/grav-plugin-admin-addon-media-metadata#17]
I have a flex-object config which uses folderStorage. When adding medatadata the plugin creates a folder in /user/pages with the name of the flex-object identifier and puts the meta json file there.

Any idea how to fix this?

here an excerpt of my blueprint
```yaml
config:
  data:
    object: 'Grav\Common\Flex\Types\Generic\GenericObject'
    collection: 'Grav\Common\Flex\Types\Generic\GenericCollection'
    index: 'Grav\Common\Flex\Types\Generic\GenericIndex'
    storage:
      class: 'Grav\Framework\Flex\Storage\FolderStorage'

form:
  validation: loose

  fields:
    media:
      type: section
      title: Medien
      underline: true
      fields:
        images:
          type: file
          label: Bilder
          limit: 0
          accept:
          - image/*
```
