### ISSUE TITLE
Metadata not updated when click on save

### ISSUE THREAD

**Issue by JS-Media-Creation** [clivebeckett/grav-plugin-admin-addon-media-metadata#26]
When I add some new content to an image and I click save and then also save the site, the whole new content is gone. Also it says "xyz.meta.yaml doesn't exist" when I uploaded a new image and click on the "i" icon.

Running GRAV 1.7.44

**Comment by bitstarr** [comment]
If the page was not safed after adding a new media, there was no path information for the plugin to know where to put the meta file. got that fixed now.

**Comment by JS-Media-Creation** [comment]
Thx for your support and work! I've tested it, but it still doesn't save new meta content..

**Comment by bitstarr** [comment]
i have no clue what's may be wrong, it's working now on my mashine. can you provide some information on recreating your issue?

**Comment by JS-Media-Creation** [comment]
I am using the latest GRAV and plugin version. The image is a WebP file, and I am attempting to assign a new "license holder" value to it (a custom field that I created). I save the value in both the plugin field and on the general page, but the value remains unchanged from before my modifications.

Should you need any further information, please don't hesitate to ask.

**Comment by bitstarr** [comment]
Can you please post your plugin config here?

**Comment by JS-Media-Creation** [comment]
`enabled: true
metadata_form:
  fields:
    -
      type: hidden
      title: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.FILENAME
      name: filename
      readonly: true
    -
      type: text
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.TITLE
      name: title
    -
      type: text
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.ALT
      name: alt
    -
      type: textarea
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.CAPTION
      name: caption
      rows: 3
    -
      type: textarea
      label: link
      name: link
    -
      type: textarea
      label: 'license holder'
      name: license_holder`

**Comment by JS-Media-Creation** [comment]
```
enabled: true
metadata_form:
  fields:
    -
      type: hidden
      title: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.FILENAME
      name: filename
      readonly: true
    -
      type: text
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.TITLE
      name: title
    -
      type: text
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.ALT
      name: alt
    -
      type: textarea
      label: PLUGIN_ADMIN_ADDON_MEDIA_METADATA.CAPTION
      name: caption
      rows: 3
    -
      type: textarea
      label: link
      name: link
    -
      type: textarea
      label: 'license holder'
      name: license_holder
```
